services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIX_ENV: prod
      PORT: 4000
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      PHX_HOST: "basedsolutions.xmp.systems" # we need to improve this to not be hardcoded...
      URL_SCHEME: "https"
      PHX_SERVER: "true"
    ports:
      - "4000:4000"
    restart: always